class CreateJoinTablePersonalMeetingStudents < ActiveRecord::Migration[6.0]
  def change
    create_join_table :personal_meetings, :students do |t|
      t.index [:personal_meeting_id, :student_id],
        # Autogenerated name is too long for SQLite so we pick a manual one :(
        name: "meeting_student_join_index"
    end
  end
end
